### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by pije76** [wildangunawan/IDX-Scrapper#2]
Saat saya menjalankan get-list-emiten.py mendapat error sbb: "`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`"

**Comment by wildangunawan** [comment]
Akan saya coba cek ya. Sementara juga di dataset sptnya ada error.

**Comment by pije76** [comment]
Terima kasih banyak pak Wildan

**Comment by pije76** [comment]
> Akan saya coba cek ya. Sementara juga di dataset sptnya ada error.
Terima kasih banyak pak Wildan.
Di getdailydata.py nya juga ada error: `
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by pije76** [comment]
> Akan saya coba cek ya. Sementara juga di dataset sptnya ada error.

Terima kasih banyak pak Wildan.
Di getdailydata.py nya juga ada error: `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by pije76** [comment]
Apakah ada kabar gembira mengenai issue ini pak @wildangunawan? :)

**Comment by wildangunawan** [comment]
Sayangnya belum. Saya sudah coba untuk debugging dan kelihatannya Cloudflare yang memblock request dari bot. Sepertinya tidak akan bisa untuk skrg, saya sudah coba pakai beberapa library lain juga.

**Comment by wildangunawan** [comment]
Update: Saya sudah coba untuk run secara manual dan kalau dijalankan di script Python akan keluar captcha. Mungkin karena itu makanya kita sudah tidak bisa ambil data JSONnya lagi. Jujur ini sangat disayangkan.

Saya akan coba untuk gali lebih lanjut dulu, mungkin jika tidak berhasil maka hidup scrapernya sampai sini aja 😁. Petinggi IDX mungkin juga ga suka dengan kita ngescrape sendiri sebab mereka juga ada opsi subscription utk akses data IDX.

**Comment by pije76** [comment]
Sungguh disayangkan kalo begitu pak :(
Mungkin kode yg dari https://github.com/tegardp/idx-scraper bisa di modifikasi dgn menggunakan url ini pak:
https://idx.co.id/data-pasar/ringkasan-perdagangan/ringkasan-saham/

**Comment by wildangunawan** [comment]
Sayangnya kemungkinan besar tidak bisa Pak. Problem kita sekarang ada di scraper yang "terhajar" dengan Cloudflare anti-bot yang melindungi web idx.co.id. Utk endpoint yang Bapak berikan sama-sama di idx.co.id maka tidak akan ada bedanya Pak.

Kalo kita bisa "membohongi" Cloudflare, harusnya sih bisa-bisa aja dijalanin scrapernya

**Comment by pije76** [comment]
Wah sayang sekali jika sudah tidak bisa pak :(
Tapi seandainya di akalin pake selenium sepertinya bisa ya pak? Kan krn json nya masih bisa di lihat dgn menggunakan browser biasa.

**Comment by wildangunawan** [comment]
Seharusnya bisa ya pak. Mungkin pak @pije76 boleh mencobanya pak :D

**Comment by pije76** [comment]
Baik pak, thanks infonya

**Comment by wildangunawan** [comment]
Ada sedikit kabar menggembirakan. Saya akhirnya bisa coba-coba main lagi dan sudah mencoba untuk menggunakan Selenium. Ternyata, asal browsernya tidak headless, kita masih bisa untuk melakukan scraping tersebut. Saya akan coba untuk melakukan update di branch selenium.

**Comment by wildangunawan** [comment]
Seleniumnya sudah selesai diimplementasikan. Seharusnya bisa dijalankan di local computer tapi tidak bisa dijalankan di cloud karena permasalahan IP.

Cloudflare otomatis ngeluarin captcha check kalau IP tersebut berasal dari suatu data center. Jadi yasudah :)
