### ISSUE TITLE
saran link scraping IDX

### ISSUE THREAD

**Issue by G4CE-Neiz** [wildangunawan/IDX-Scrapper#3]
Salam,

Saya iseng-iseng aja mencoba scrapper ini dan mencoba memahami prosesnya. Saya pertamanya coba coba untuk google link scrapper yang digunakan, rupanya "sumber" nya mengambil langsung dari bagian profil perusahaan tercatat. saya mencoba melakukan teknik yang sama di bagian ringkasan saham yang memiliki data saham lebih lengkap dari pada info perdagangan dari profil perusahaan. berikut link yang saya dapatkan.

"https://www.idx.co.id/umbraco/Surface/TradingSummary/GetStockSummary?Length=10000&date=20210924&_=1632667358097"

seluruh detail dari saham seluruh emiten yang ada di BEI dapat terpapar dengan 1 link ini. dengan kelemahan bagian date dari link yang harus selalu rolling untuk mendapatkan datanya. saya juga menemukan bahwa jejak digital paling awal dari BEI ada pada tanggal 2 januari 2015.

sekian atas informasi yang bisa saya berikan
semoga bisa membantu

**Comment by wildangunawan** [comment]
Halo mas/mbak.

Terima kasih link sarannya. Saya akan coba untuk ulik lebih lanjut besok,
namun saya tidak bisa menjanjikan apapun.

Saat ini, website IDX.co.id dijaga ketat oleh Cloudflare, sepertinya tim IT
IDX selalu menyalakan mode Under Attack yang membuat Cloudflare benar-benar
memblok semua request dari bot.

Saya rasa ini sangat wajar dilakukan oleh IDX mengingat mereka juga
"jualan" data market. Kalau ternyata scraper bisa ngambil secara gratis
maka pasti akan membahayakan service mereka tersebut.

Saya sebelumnya menggunakan library Cloudscraper untuk mem-bypass
verifikasi 5 detik Cloudflare, namun saat Under Attack dinyalakan, semua
akses mencurigakan wajib melalui Captcha mereka.

Dengan demikian, semua file, API, atau apapun itu yg tercover dalam proxy
Cloudflare tidak akan bisa diakses oleh scraper.

Salah satu cara yang mungkin ampuh adalah mencari tau IP address server
IDX, jadi kita bisa mem-bypass Cloudflare. Namun sampai sekarang saya
sendiri juga belum menemukan titik terang apapun.

Pada tanggal Min, 26 Sep 2021 23.13, G4CE-Neiz ***@***.***>
menulis:

**Comment by wildangunawan** [comment]
Saya sudah mencobanya di Postman dan benar bahwa request dari bot tetap ditolak oleh Cloudflare.

![image](https://user-images.githubusercontent.com/35158077/134839540-9082f991-80c1-4d39-86f8-7d2b65c67d95.png)

Terima kasih banyak sarannya, namun sayang sekali ini 95% tidak mungkin untuk dapat di-bypass kecuali orang IDX yang membukakan akses secara langsung.
