### ISSUE TITLE
cannot make cloudscraper.CloudScraper()

### ISSUE THREAD

**Issue by rizkynat** [wildangunawan/IDX-Scrapper#4]
i use cloudscraper.create_scraper()
https://stackoverflow.com/questions/65604551/cant-bypass-cloudflare-with-python-cloudscraper

**Comment by wildangunawan** [comment]
It doesn't work mas. IDX returned 403 which is forbidden. I don't think this scraper will work anymore except IDX drop their Cloudflare protection.

![image](https://user-images.githubusercontent.com/35158077/139641811-37bd329c-0912-46ea-8783-faf4fdfb4943.png)

**Comment by wildangunawan** [comment]
Merge dengan #2
