### ISSUE TITLE
Error invalid syntax

### ISSUE THREAD

**Issue by fikar46** [wildangunawan/IDX-Scrapper#6]
SyntaxError: invalid syntax
mzulfikarmaylendra@zulfikar src % python get-list-emiten.py
  File "get-list-emiten.py", line 36
    link = f"https://idx.co.id/umbraco/Surface/StockData/GetSecuritiesStock?code=&sector=&board=&start={start}&length={length}"
    
   Ini setealh menjalankan python get-list-emiten.py

**Comment by danendral** [comment]
I got the similar error, seems that the link is broken. Is historical price data no longer available in idx?

**Comment by danendral** [comment]
@wildangunawan

**Comment by wildangunawan** [comment]
Apologies, I didn't realized that I have an issue.

@fikar46, probably there is an error in the script.
@danendral, yes, last time I tried link has changed. You can inspect where request being sent to when they're fetching their data in IDX website.

**Comment by wildangunawan** [comment]
New link: 
1. `https://idx.co.id/primary/TradingSummary/GetStockSummary?length=9999&start=0` gets last trading day data
2. `https://idx.co.id/primary/TradingSummary/GetStockSummary?length=9999&start=0&date=20230223` gets trading data at date given (YYYYMMDD)

**Comment by wildangunawan** [comment]
> SyntaxError: invalid syntax mzulfikarmaylendra@zulfikar src % python get-list-emiten.py File "get-list-emiten.py", line 36 link = f"[https://idx.co.id/umbraco/Surface/StockData/GetSecuritiesStock?code=&sector=&board=&start={start}&length={length}](https://idx.co.id/umbraco/Surface/StockData/GetSecuritiesStock?code=&sector=&board=&start=%7Bstart%7D&length=%7Blength%7D)"
> 
> Ini setealh menjalankan python get-list-emiten.py

Utk ini, saya pakai [f-string](https://peps.python.org/pep-0498/) dan baru disupport Python 3.6 ke atas. Bisa dicoba lagi dengan Python versi lain ya.
